程序执行过程中发生了不正常的情况，而这种不正常的情况叫做：异常

java语言是很完善的语言，提供了异常的处理方式，java把异常信息打印输出到控制台，程序员看到异常信息后，可以对程序进行修改，**让程序更加健壮**

控制台打印出来的异常信息**是由jvm打印**出来的

1.Java中异常**以类的**形式存在，每一个异常类都可以创建异常对象。

```java
public class Demo25 {
    public static void main(String[] args) {
        //通过异常类来实例化异常对象
        NumberFormatException nfe=new NumberFormatException("数字格式化异常");
     //异常为:java.lang.NumberFormatException: 数字格式化异常
        System.out.println(nfe);
        //通过异常类来创建异常
        NullPointerException npe=new NullPointerException("空指针异常");
        //java.lang.NullPointerException: 空指针异常
        System.out.println(npe);
    }
}
```

## 异常继承结构

**不管是错误还是异常都是可以抛出的**

Throwable类可以分为Error(错误)和Exception(异常)两个子类

Error:所有错误只要发生，java程序只有一个结果那就是终止程序的执行。退出JVM错误是不能处理的.

Exception:直接子类为ExceptionSubClass。所有Exception的直接子类都叫做编译时，都叫做编译时异常，又叫做受检异常或受控异常。第二个子类为RuntimeException。所有RuntimeException及子类的错误叫**做运行异常**.又叫做********非受控异常或未受检异常。********

**所有Exception的直接子类，都叫做编译时异常。编译时异常是在编译阶段发生的吗？不是。编译时异常是表示必须在编写程序时候优先对这种异常进行处理，如果不处理编译器将会报错。**

所有**RuntimeException及运行时异常**。运行时异常阶段，你可以选择处理，也可以选择不处理。

编译时异常和运行时异常，都是发生在运行阶段。编译阶段异常是不会发生的。

编译时异常因为什么而得名？**因为编译时异常必须在编译（编写）阶段预先处理，如果不处理则会报错。由于异常都是在运行阶段发生的。因为只有程序运行阶段才可以new对象。因为异常的发生就是new异常对象。**

编译时异常和运行时异常的区别：编译时异常一般发生概率较高，需要在运行之前进行处理。运行时异常一般发生的概率比较低。

## java处理异常的两种方式

1. 在方法声明的位置上，使用throws关键字
2. 第二种方式使用try...catch语句进行异常的捕捉

注意：java中异常发生之后如果一直上抛，最终抛给了main方法，main方法继续往上抛，抛给了调用者jvm，jvm知道这个异常的发生，只有一个结果。终止java程序的执行。

```java
public class ExceptionTest03 {
    public static void main(String[] args) {
        /*
        * 程序执行到此处发生了ArithmeticException异常，
        * 底层new了一个ArithmeticException异常对象
        * 然后抛出了，由于main方法调用了100/0，所以这个
        * 异常.ArithmeticException抛给了main方法
        * main方法继续往上抛，抛给了调用者jvm，jvm知道这个异常的发生，
        * 只有一个结果。终止java程序的执行。
        * */
        System.out.println(100/0);
    }
}
```

```java
public class ExceptionTest03 {
    /**
     * 以下代码报错原因是
     * 因为在doSome方法上声明了throws ClassNotFoundException
     * 我们调用必须对这种异常进行预处理，若不处理编译器就会报错
     * 报错信息：java.lang.ClassNotFoundException;
     * */
    public static void main(String[] args) {
        doSome();
    }
    /*
    * dosome在方法声明位置上使用了throws ClassNotFoundException
    * 这个代码表示doSome方法在执行过程中可能会出现：ClassNotFoundException
    * 叫做类没找到异常，这个异常父类是Exception
    * 我们在调用doSome()方法的时候必须对这种异常进行预先异常处理
    * */
    public static void doSome() throws ClassNotFoundException{
        System.out.println("azhe");
    }
}

```

## 异常处理的原理

第一种处理方式上抛

```java
public static void main(String[] args) throws ClassNotFoundException {
        doSome();
    }
    
    public static void doSome() throws ClassNotFoundException{
        System.out.println("azhe");
    }
```

第二种处理方式try..catch

```java
 public static void main(String[] args)  {
        try {
            doSome();
        }catch (ClassNotFoundException e){
            e.printStackTrace();
        }
    }

    public static void doSome() throws ClassNotFoundException{
        System.out.println("azhe");
    }
```

第一种方式相当于继续把异常传递给调用者

第二种方式try..catch进行捕捉，等于把异常真正拦截下来了，异常真正解决了调用者都不知道

注意：只有异常没有捕捉，采用上报得方式，此方法得后续代码不会执行。另外需要注意，**try语句中得某一行出现异常，该行后面的代码不会执行**。**try...catch捕捉异常后，后续代码可以执行**。下面这个例子

## 深入try..catch

```java
  public static void main(String[] args)  {
        try {
            FileInputStream fis=new FileInputStream("H:\\Cnm1\2002");
            System.out.println("以上出现异常这里无法执行");
        }catch (FileNotFoundException e){
            System.out.println("这里执行");
        }
        System.out.println("这里又能执行");
    }
```

```
这里执行
这里又能执行
```

```java
 try {
             FileInputStream fis=new FileInputStream("H:\\Cnm1\2002");
             System.out.println("11");
         }catch (IOException e){//相当于多态：IOException e=new FileNotFoundException();
             System.out.println("就这");
         }
```

就这

同理以上方式也适用于Exception(所有异常得父类)，也是运用了多态

try...catch也可以套娃，可以用exception一步解决，但是更多的则是使用分布(将异常一个一个写出来)也就是套娃，但是只执行第一个catch。而且**catch提取得错误必须是从小到大得顺序进行分支**，先写子类再写父类

```java
try {
           FileInputStream fis=new FileInputStream("H:\\Cnm1\2002");
            fis.read();
        }catch (FileNotFoundException e){//相当于多态：IOException e=new FileNotFoundException();
            System.out.println("只执行这个");
        }catch (IOException I){
            System.out.println("不执行输出");
        }
```

```
只执行这个
```

```java
try {
           FileInputStream fis=new FileInputStream("H:\\Cnm1\2002");
            fis.read();
        }catch (IOException I){
            System.out.println("不执行输出");
        }catch (FileNotFoundException e){//相当于多态：IOException e=new FileNotFoundException();
            System.out.println("只执行这个");
        }//这样会报错，FileNotFoundException是IOException得子类
```

**所有多分支写法一定要先写子类再写父类**

 java8新特性：可以使用|

```java
try {
           FileInputStream fis=new FileInputStream("H:\\Cnm1\2002");
            System.out.println(100/0);//这里本应该是数学异常，但由于特性就不报错了
        }catch (FileNotFoundException | ArithmeticException | NullPointerException e){
            System.out.println("只执行这个");
        }
```

## 异常得两个重要方法

1.获取异常简单的描述信息：

```java
String msg=exception.getMessage();
```

2.打印异常追踪得堆栈信息

```java
exception.printStackTrace();
```

```java
public static void main(String[] args) {
        //创建一个异常对象,中间这个字符串用来描述这个异常对象
        //这里只是new了个异常，并没有抛出，jvm认为只是一个普通java对象
        NullPointerException e=new NullPointerException("空指针异常");
        //获取异常简单的描述信息：信息就是对象里得字符串
        String message = e.getMessage();
        System.out.println(message);
        //打印异常追踪得堆栈信息
        e.printStackTrace();
    }
```

```java
空指针异常
java.lang.NullPointerException: 空指针异常
	at Error.ExceptionTest04.main(ExceptionTest04.java:7)

```

注意:这里面打印异常堆栈信息这个方法，采用了**异步线程**得方式打印得。

方法实例的练习：

```java
public static void main(String[] args) {
        try {
            m1();
        } catch (FileNotFoundException e) {
            //打印异常得堆栈信息，如果打印的是空就说明已经捕获异常并解决
            e.printStackTrace();
        }
    }
    private static void m1() throws FileNotFoundException {
        m2();
    }
    private static void m2() throws FileNotFoundException {
        m3();
    }
    private static void m3() throws FileNotFoundException {
        new FileInputStream("H:\\Cnm1");//因为没有权限
    }
```

```
java.io.FileNotFoundException: H:\Cnm1 (拒绝访问。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Error.ExceptionTest04.m3(ExceptionTest04.java:25)
	at Error.ExceptionTest04.m2(ExceptionTest04.java:21)
	at Error.ExceptionTest04.m1(ExceptionTest04.java:17)
	at Error.ExceptionTest04.main(ExceptionTest04.java:9)
```

```java
public static void main(String[] args) {
        try {
            m1();
        } catch (FileNotFoundException e) {
            //打印异常得堆栈信息，如果打印的是空就说明已经捕获异常并解决
            e.printStackTrace();
        }
        //这里程序会执行，服务器不会报异常，
        System.out.println("Hello World");
    }

    private static void m1() throws FileNotFoundException {
        m2();
    }

    private static void m2() throws FileNotFoundException {
        m3();
    }

    private static void m3() throws FileNotFoundException {
        new FileInputStream("H:\\Cnm1");
    }
```



我们以后查看异常的追踪信息，应该怎么看，可以快速调试程序？

异常信息追踪信息，从上往下看

## try..catch..finally

1.在finally子句中的代码是最后执行的，并且是一定会执行的，即使try语句中的代码出现了异常。

finally的使用1.

```java
public static void main(String[] args) {
        //开始读取文件,这个变量得在外面否则finally无法识别
        FileInputStream fis = null;
        try {
            fis=new FileInputStream("H:\\java");
            System.out.println("这里不会输出");
             //开始读取文件
            String s=null;
            //这里肯定会空指针异常
            s.toString();//如果这行出现了异常那后面流就不会被关闭
            //因为finally必须执行，所以去finally关闭
            fis.close();

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }finally {
            System.out.println("这里肯定输出");
            if (fis!=null){
                try {
                    //close()方法有异常所以得独立try catch
                    fis.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        System.out.println("这里也会输出");
    }
```

```
java.io.FileNotFoundException: H:\java (拒绝访问。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Error.ExceptionTest06.main(ExceptionTest06.java:12)
这里肯定输出
这里也会输出
```

finally语句使用情况：通常在finally语句中**完成资源得释放/关闭。**

因为finally代码比较有保障，**即使try语句中代码出现异常，finally代码中也会正常运行**

try和finally没有catch，可以执行吗？可以

以下代码执行顺序：执行顺序try>finally>return（**return只要执行方法肯定结束**）

```java
//执行顺序try>finally>return
try {
            System.out.println("执行");
            return;
        }finally {
            System.out.println("执行");
        }
```

```
执行
执行
```

但是**切记try不能单独使用，但是try.,, finally可以*****但是finally后面得代码就无法执行了****

```java
try {
            System.out.println("执行");
            return;
        }finally {
            System.out.println("执行");
        }
        //这里无法执行
        System.out.println("这里无法执行");
```

唯一能使finally不执行的语句就是退出jvm

```java
try {
            System.out.println("执行");
            //退出jvm
            System.exit(0);
        }finally {
            System.out.println("不执行");
        }
```

## **特别注意**：java中亘古不变的·语法：

1.**方法中的代码必须遵循自上而下的语法执行**

2、**return语句一旦执行，整个方法必须结束**

```java
public static void main(String[] args) {
        //因为java中有一条语法，是至上而下执行的，所有i必须为100
        //但是呢他的顺序又是try>finally>return
        System.out.println(m1());
    }
    public static int m1(){
        int i=100;
        try{
            return i;
        }finally {
            i++;
        }
    }
```

```
100
```

## **final finally finalize的区别**

final:关键字

finally:与try连用常用于异常机制处理中

finalize:标识符，一个方法，垃圾回收机制的

## java中自定义异常

1.编写一个类继承Exception(编译时异常）或者RuntimeException（运行时异常）

2.提供两个构造方法，一个无参数的，一个带有String参数的

```java
public static void main(String[] args) {
        //创建异常对象，并没有手动抛出
        MyException e=new MyException("未找到指定用户");
        //打印堆栈信息
        e.printStackTrace();
        //获取简单异常描述信息
        String ms= e.getMessage();
        System.out.println(ms);
    }
```

```java
Error.MyException: 未找到指定用户
	at Error.ExceptionTest07.main(ExceptionTest07.java:6)
未找到指定用户
```

**异常在项目中主要应用与某个方法不能执行时，不使用return；而是把他创作为异常对象跑出去，将return；换成throw new 异常("描述异常");**

## 异常的覆盖

在继承中，子类的异常只能比父类的异常更少或者相等，不能比父类多

throw手动抛出异常
